### PR TITLE
LRQA-71000 Enable PoshiPauseUsageCheck for now for all branches

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
[v](ci:forward)

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by felix3508** [comment]
ci:test:stable

**Comment by felix3508** [comment]
ci:test:stable

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Passed [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430248837)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by felix3508** [comment]
ci:forward:force

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/141453

**Pull request closed without merging**
