### PR TITLE
LPS-204924 Move package, *TestUtil.java should be in test.util

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Acoording to testray-results.csv, No Unique Failures.
[testray-results.csv](https://github.com/ling-alan-huang/liferay-portal/files/13867600/testray-results.csv)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
