### PR TITLE
LPS-105380_DTOEnumCreationCheck_20210916_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hi @Preston-Crary I got a lot of `missing language key` errors, these probably relate to https://github.com/brianchandotcom/liferay-portal/pull/107236, can you have a look?
or should we(SF) do something for that?
Thanks.

/cc @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
google-authorization-configuration-name is fine since it's using the GoogleAuthorizationConfiguration.class to get the correct bundle.
ntlm-configuration-name is fine since it's in the same bundle.
more-global-results is missing before LPS-135504.
add-existing-order-type is missing before LPS-135504.
find-an-order-type is somewhat new and missing.

**Pull request closed without merging**
