### PR TITLE
LPS-200190 Enforce commit message style for breaking change

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://liferay.slack.com/archives/CL69D8RUG/p1695116917497289

/cc @almonwork

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the test failures? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/143795

**Comment by qz1010** [comment]
see #2267

**Pull request closed without merging**
