### PR TITLE
LPS-200190 Enforce commit message style for breaking change

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Rebase and resent: https://github.com/ling-alan-huang/liferay-portal/pull/2259

**Pull request closed without merging**
