### PR TITLE
LPS-189837 Prevent multithreading issue when reading XML

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
@ling-alan-huang I think the second commit is necessary, because SourceUtil.readXML can' t throw exception when read xml file now. We should assert document not equal null or move assign rootElement to try block

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/2046

**Pull request closed without merging**
