### PR TITLE
LPS-154677 SF, remove nonexistent package

### PR DESCRIPTION
**Pull request by ling-alan-huang**
see e6cc8b9e36ef797825a6d3d1a261438945bb2b7e

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@jaydawu Can you help check the test failures? Thanks.

**Comment by jaydawu** [comment]
Sure thing. @ling-alan-huang

**Comment by jaydawu** [comment]
Hello @ling-alan-huang 
After checking, there are no relevant errors to this pull. This pull should be good to go. Thanks!

**Comment by ling-alan-huang** [comment]
Thanks @jaydawu

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/128967

**Pull request closed without merging**
