### PR TITLE
LPS-105380 Every test method must have an @override in *ResourceTest.java

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Two kinds of Violations:
```
Test method testUpgradeCalendarResourceUserId must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/calendar/calendar-test/src/testIntegration/java/com/liferay/calendar/upgrade/v1_0_5/test/UpgradeCalendarResourceTest.java 71 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testUpgradeCalendarUserId must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/calendar/calendar-test/src/testIntegration/java/com/liferay/calendar/upgrade/v1_0_5/test/UpgradeCalendarResourceTest.java 86 (SourceCheck:JavaTestMethodAnnotationsCheck)

Test method testGetKeywordsRankedPageWithPagination must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-admin-taxonomy/headless-admin-taxonomy-test/src/testIntegration/java/com/liferay/headless/admin/taxonomy/resource/v1_0/test/KeywordResourceTest.java 67 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testGetSegmentUserAccountsEmptyPage must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/SegmentUserResourceTest.java 56 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testGetSegmentUserAccountsPageWithNonexistingSegmentId must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/SegmentUserResourceTest.java 88 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testGetSiteSegmentsPageWithDefaultPermissions must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/SegmentResourceTest.java 92 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testGetSiteSegmentsPageWithoutViewPermissions must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/SegmentResourceTest.java 120 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testPostSiteBlogPostingImageRollback must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/BlogPostingImageResourceTest.java 43 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testPutSiteMessageBoardMessageWithoutParentMessageId must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/MessageBoardMessageResourceTest.java 52 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testPutSiteWikiPageWithoutNodeId must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/WikiPageResourceTest.java 60 (SourceCheck:JavaTestMethodAnnotationsCheck)
Test method testGraphQLGetProcessProcessVersionsPage must have an annotation @Override: /home/alan/liferay_code/master/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-test/src/testIntegration/java/com/liferay/portal/workflow/metrics/rest/resource/v1_0/test/ProcessVersionResourceTest.java 109 (SourceCheck:JavaTestMethodAnnotationsCheck)

```

Hey @hhuijser,

I just found the `Base*ResourceTestCase` is generated code, do you know how to generate them and add methods?


_**Violation 1:**_
See [testUpgradeCalendarResourceUserId()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-test/src/testIntegration/java/com/liferay/calendar/upgrade/v1_0_5/test/UpgradeCalendarResourceTest.java#L72)
and 
[testUpgradeCalendarUserId()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-test/src/testIntegration/java/com/liferay/calendar/upgrade/v1_0_5/test/UpgradeCalendarResourceTest.java#L87)

Class `UpgradeCalendarResourceTest` doesn't have base class, so `testUpgradeCalendarResourceUserId()` and `testUpgradeCalendarUserId()` can't have `@Override` annotations.


_**Violation 2:**_
See [testGetSegmentUserAccountsEmptyPage()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/SegmentUserResourceTest.java#L57)

`testGetSegmentUserAccountsEmptyPage()` should have `@Override`, but the base class [BaseSegmentUserResourceTestCase](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/BaseSegmentUserResourceTestCase.java) doesn't have `testGetSegmentUserAccountsEmptyPage()`.

**Comment by hhuijser** [comment]
@ling-alan-huang 
- Send you slack message regarding how to generate
- We should only apply to classes in `/resource/v*.*/`, so we can skip the two cases in `calendar`
- Violation 2, when the base class doesn't have that method, we should try to add the logic in a method with the same name and use `super.methodName` (check Brian's comment that started this whole thing)

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Pull request closed without merging**
