### PR TITLE
LPS-169488: Jsp variable name check | 9

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Jeremy-Ch I need your help, can you help check the test failures. Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by Hanlf** [comment]
@ling-alan-huang , I checked the latest relevant results, the failures are not related to this PR.

**Pull request closed without merging**
