### PR TITLE
LPS-163590 Remove JSONPackageJSONRedundantDependenciesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@JanisZhang @dantewang
Can you help fix SF issue?
It's a time issue.

see 
https://github.com/liferay/liferay-portal/commit/73f2a3f414#diff-967a46bafa2036c78c2d3c5c2ad04e624b891d7821d882f38564650ca3131f98R346 https://github.com/liferay/liferay-portal/commit/924b3d471e56d962b60486defb2ba81d09928618#diff-9339a9b15ec5242c9f0236bc00e01638651d37b471ce252960ffb713d6fd9e06L97

They go the same day, but different time.

**Comment by JanisZhang** [comment]
@ling-alan-huang, I will fix it.  
cc/ @dantewang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
