### PR TITLE
LPS-196539 Renaming for type PortletPreferences

### PR DESCRIPTION
**Pull request by ling-alan-huang**
/cc @qz1010

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the test result? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

Fetched the commit and tried to build a bundle in local. Build failed.
```
compile-common-jsp:
     [java] Changes to environment variables are ignored when same JVM is used.
     [echo] Sep 26, 2023 1:38:59 PM org.apache.jasper.servlet.TldScanner scanJars
     [echo] INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
     [echo] Sep 26, 2023 1:38:59 PM org.apache.jasper.JspC execute
     [echo] INFO: Generation completed with [0] errors in [636] milliseconds
    [javac] Compiling 177 source files to /home/liferay/project/liferay-portal/portal-web/classes/tomcat
    [javac] /home/liferay/project/liferay-portal/portal-web/classes/tomcat/org/apache/jsp/html/portal/header_005fportlet_jsp.java:611: error: variable portletPreferences is already defined in method _jspService(HttpServletRequest,HttpServletResponse)
    [javac] PortletPreferences portletPreferences = themeDisplay.getStrictLayoutPortletSetup(layout, portletId);
    [javac]                    ^
    [javac] /home/liferay/project/liferay-portal/portal-web/classes/tomcat/org/apache/jsp/html/portal/render_005fportlet_jsp.java:598: error: variable portletPreferences is already defined in method _jspService(HttpServletRequest,HttpServletResponse)
    [javac] PortletPreferences portletPreferences = themeDisplay.getStrictLayoutPortletSetup(layout, portletId);
    [javac]                    ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors

BUILD FAILED
/home/liferay/project/liferay-portal/build.xml:208: The following error occurred while executing this line:
/home/liferay/project/liferay-portal/build.xml:367: The following error occurred while executing this line:
/home/liferay/project/liferay-portal/portal-web/build.xml:243: The following error occurred while executing this line:
/home/liferay/project/liferay-portal/portal-web/build.xml:227: The following error occurred while executing this line:
/home/liferay/project/liferay-portal/portal-web/build.xml:184: Compile failed; see the compiler error output for details.

Total time: 9 minutes 58 seconds
f
```

**Comment by qz1010** [comment]
@SylviaLuan Thanks. It's my bad.
see #2163

**Pull request closed without merging**
