### PR TITLE
LPS-195894 Use Objects.equals on method

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Can you help check the failures? Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Passed. [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440178473)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/142155

**Pull request closed without merging**
