### PR TITLE
LPS-203507 Fix SF bug for enforcing an empty line

### PR DESCRIPTION
**Pull request by ling-alan-huang**
see https://github.com/ling-alan-huang/liferay-portal/commit/215b8938d4e7d53bdd1ce9a84923b4027c8135cb

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
