### PR TITLE
LPS-185667 SF, avoid stale object

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Hanlf Can you help scan the test failures? Thanks.

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
