### PR TITLE
LPS-206502 Enforce variable name for ServiceTrackerMap

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the test failures? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
