### PR TITLE
LPS-171011 Update includeresource

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
@ling-alan-huang - I need your help to test this fix, I couldn't reproduce this issue locally. If the test throws different CNFE errors, those new classes can be added in the same way.

This was caused by cdd831b0. There's a bunch of imports that were added to LocaleThreadLocal.java.

In my opinion, the real issue is using the default version in [build.gradle](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/build.gradle#L46). I think it should be set to an explicit version to avoid unexpected regression issues.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/1567 with other SF fix.

**Pull request closed without merging**
