### PR TITLE
LPS-156857 Meaningless code

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the test failurs? Thanks.

**Comment by austinchiang** [comment]
Looks unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
