### PR TITLE
Lps 127030

### PR DESCRIPTION
**Pull request by mtambara**
HI @ling-alan-huang I made some changes to the test rule, here are the updated SF rules:

1. `LiferayUnitTestRule` should be applied to every unit test (tests under a `*/test/*` or `*/test/unit/*` folder) except tests that use `@RunWith(PowerMockRunner.class)`.
2. Right now, SF doesn't need to restrict usages of `FileUtil.setFile(new FileImpl())` or `PropsUtil.setProps(new PropsImpl())`, let's focus on getting the rule applied everywhere first.
3. Ideally the SF rule will apply `LiferayUnitTestRule` globally, but if that's too difficult then apply to as many tests as possible and log the tests that need manual additions (tests using AggregateTestRule).

I still need to test functionality so I may update this pull, but the SF rule shouldn't be affected by that. Let me know if you have any questions

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:backend

**Comment by ling-alan-huang** [comment]
@mtambara I added a new SF rule, I can see 1000+ test files that need manual changes.
see SF failures: https://github.com/ling-alan-huang/liferay-portal/pull/368

**Comment by mtambara** [comment]
@ling-alan-huang Can you send me a pull with the new SF rule? I'll apply the fixes

**Comment by ling-alan-huang** [comment]
Sent pull: https://github.com/mtambara/liferay-portal/pull/1039

**Pull request closed without merging**
