### PR TITLE
LPS-177111 SF, directly assign variables

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the tests? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
The failure not related to this pull request.
[ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422540709)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
