### PR TITLE
LPS-204967 Skip checking unused @reference variable from allowedUnusedReferenceVariableDirNames

### PR DESCRIPTION
**Pull request by qz1010**
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/146032
/cc @JanisZhang

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the tests? Thanks.
@austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
Do not squash non conficts commits. Please resend.

**Comment by qz1010** [comment]
resend #2402

**Pull request closed without merging**
