### PR TITLE
sf_test

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Can you look into this?
If you run Sf on this file, you'll see it's incorrectly sorting this description

**Comment by hhuijser** [comment]
@ling-alan-huang can you give this one priority? Thanks

**Comment by ling-alan-huang** [comment]
@hhuijser, I am looking into this now.

**Comment by ling-alan-huang** [comment]
Closing, sent to Hugo for review: https://github.com/hhuijser/liferay-portal/pull/3805

**Pull request closed without merging**
