### PR TITLE
LPS-203981 Fix SF bug in getting variable type

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

The failures not related to this pull request. You can forward this pr with `ci:forward:force`
[ci:test:relevant](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2475530162&testrayRunId=2475530209)

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
