### PR TITLE
LPS-177111 SF, directly assign variables

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan
Please help scan the test result, thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Passed [ci:test:relevant](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2426740606)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
