### PR TITLE
LPS-199559 Format cdata-value in Json

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
I will fix SF issue when the new version of poshi-core is released.
@SylviaLuan Are relevant test failures releated to this PR?
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

Found a related issue:
[com.liferay.portal.workflow.kaleo.definition.util.WorkflowDefinitionContentUtilTest
](https://testray.liferay.com/home/-/testray/case_results/2448670819)
```
[beanshell]      [exec] com.liferay.portal.workflow.kaleo.definition.util.WorkflowDefinitionContentUtilTest > testCDATAToXML FAILED
[beanshell]      [exec]     java.lang.AssertionError
[beanshell]      [exec]         at org.junit.Assert.fail(Assert.java:86)
[beanshell]      [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
[beanshell]      [exec]         at org.junit.Assert.assertTrue(Assert.java:52)
[beanshell]      [exec]         at com.liferay.portal.workflow.kaleo.definition.util.WorkflowDefinitionContentUtilTest.testCDATAToXML(WorkflowDefinitionContentUtilTest.java:120)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[beanshell]      [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[beanshell]      [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[beanshell]      [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[beanshell]      [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[beanshell]      [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[beanshell]      [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[beanshell]      [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[beanshell]      [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[beanshell]      [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[beanshell]      [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[beanshell]      [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[beanshell]      [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
[beanshell]      [exec]         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
[beanshell]      [exec]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
[beanshell]      [exec]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
[beanshell]      [exec]         at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
[beanshell]      [exec]         at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the test failures?
Just the failures from ci:test:relevant.
Thank you.

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

ci:test:relevant passed.

**Comment by ling-alan-huang** [comment]
Thanks @SylviaLuan 
see https://github.com/brianchandotcom/liferay-portal/pull/143048

**Pull request closed without merging**
