### PR TITLE
LPD-5341 Only enable for master for now

### PR DESCRIPTION
**Pull request by ling-alan-huang**
/@kevhlee SF complains on 7.x, please revert my changes if you have plan to fix the violations on 7.x.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by kevhlee** [comment]
Hi @ling-alan-huang, thanks for letting me know! I have to take a look but I plan on fixing the violations for the 7.x branches because the bug that the SF rule is preventing is most likely impacting those branches as well.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
