### PR TITLE
LPS-188769 Do not include the header Liferay-Require-SchemaVersion when the service.xml only contains empty entity with no columns

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Wa1ter-Shao Can you help scan the failrues? Thanks.
/cc @felix3508 @austinchiang

**Comment by Wa1ter-Shao** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by Wa1ter-Shao** [comment]
ci:stable

**Comment by Wa1ter-Shao** [comment]
ci:test:stable

**Comment by Wa1ter-Shao** [comment]
Hello @ling-alan-huang ,

I don't think the failed cases in relevant test are related to this pull. I think we can forward it once stable test pass.

/cc @felix3508 @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
