### PR TITLE
LPS-177111 SF, use set calls 

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:foward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the test? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Passed [ci:test:relevant](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2429328695)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
