### PR TITLE
LPS-161695 SF rule to initialize the Release for web modules

### PR DESCRIPTION
**Pull request by achaparro**
Hi @ling-alan-huang @qz1010,

I added some changes, please verify if _JavaUpgradeVersionSourceProcessorTest_ works and let me know if you need anything else.

Thank you!

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by achaparro** [comment]
@vicnate5 @susanchen3 is this pull good to go?

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by susanchen3** [comment]
Test failures are unrelated :heavy_check_mark: Looks good to manually forward from QA perspective :rocket:

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/124764

**Pull request closed without merging**
