### PR TITLE
LPS-193718 Smoke tests should always set property "ci retries disabled" true in definition

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Splitted LPS-188912 in https://github.com/ling-alan-huang/liferay-portal/pull/2067

**Comment by ling-alan-huang** [comment]
see https://github.com/qz1010/liferay-portal/pull/64

**Pull request closed without merging**
