### PR TITLE
LPS-201445 delete missing empty line before assign in MissingEmptyLineCheck

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see https://liferay.atlassian.net/browse/LPS-201445

**Pull request closed without merging**
