### PR TITLE
LPS-199829 Move properties to root directory, apply GradleDependencyArtifactsCheck to all portal code

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the test result? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Passed! [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2446076360)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
Thank you @SylviaLuan, see https://github.com/brianchandotcom/liferay-portal/pull/142693

**Pull request closed without merging**
