### PR TITLE
LPS-185027: Format close tag in ftl file

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Waiting for https://github.com/ling-alan-huang/liferay-portal-ee/pull/707 https://github.com/ling-alan-huang/liferay-portal-ee/pull/708 https://github.com/ling-alan-huang/liferay-portal-ee/pull/709 to be merged.

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/1884

**Pull request closed without merging**
