### PR TITLE
LPS-147890 SF rule to avoid incorrect usages after LPS-149180

### PR DESCRIPTION
**Pull request by achaparro**
Hi @ling-alan-huang, @qz1010,

The code looks good to me, just one thing:
- Is it possible to remove the [unnecessary ifs](https://github.com/ling-alan-huang/liferay-portal/pull/1500/files#diff-bb00cc8ca734a76053952a1a749fbcd3dc4295e156f685e2e1dbc6efea109dbbR49) from the code automatically? (if this makes the code too complex is fine to show a warning as we are doing now)

Thank you very much for your work because it seems a complex change, this will help us a lot!

cc/ @luisortiz89

PS: In the future, please send the pull to the [liferay-uniform](https://github.com/liferay-uniform/liferay-portal/pulls) user since, in that way, any person in the team will be able to help you :-)

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
hey @ling-alan-huang, are the sf errors related?

**Comment by ling-alan-huang** [comment]
@achaparro

I added the last two commits for wordsmith changes and resent here: https://github.com/liferay-uniform/liferay-portal/pull/795

We have to keep the subchecks in order(they are implemented by checkstyle, which is always show warning instead of auto changing), so we can't remove the unnecessary if-statement automatically.

**Comment by ling-alan-huang** [comment]
o, let me check the SF issues.

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull reuqest.

**Pull request closed without merging**
