### PR TITLE
LPS-147683 Enforce jaxrs name for source formatter

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
这个代码有没有影响？
https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-remote/portal-remote-jaxrs-whiteboard-debug/src/main/java/com/liferay/portal/remote/jaxrs/whiteboard/debug/osgi/commands/JaxRsServiceRuntimeOSGiCommands.java#L135-L138

**Comment by ling-alan-huang** [comment]
see: https://github.com/ling-alan-huang/liferay-portal/pull/699

**Pull request closed without merging**
