### PR TITLE
LPS-204967 Skip checking unused @reference variable from allowedUnusedReferenceVariableDirNames

### PR DESCRIPTION
**Pull request by qz1010**
/cc @JanisZhang

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
ci:forward

**Comment by JanisZhang** [comment]
@qz1010 Thanks!

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the test failures from PRs below? Thanks.
/cc @austinchiang

**Comment by Wa1ter-Shao** [comment]
Passed review, failed cases are not related to this pull.
I think the risk of this pull is low, we can forward it directly.

/cc @SylviaLuan

**Comment by qz1010** [comment]
ci:forward:force

**Pull request closed without merging**
