### PR TITLE
LPS-195894 SF, use Objects.equals on method - portal-impl

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Please help scan the failures, thanks.

**Comment by SylviaLuan** [comment]
Passed [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2425557793)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
