### PR TITLE
LPS-166481 Add setGlobalParameter

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hi @austinchiang
This is not a real PR, but I really need your help to check the test failures. Thanks.

**Comment by austinchiang** [comment]
@ling-alan-huang I checked the test failures, nothing seems unique/related

**Comment by ling-alan-huang** [comment]
Thanks @austinchiang

**Pull request closed without merging**
