### PR TITLE
LPS-191902 Add check to avoid deploy test util jar into production code

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF request: https://github.com/brianchandotcom/liferay-portal/pull/137756

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Please help scan the failures, thanks.

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
