### PR TITLE
LPS-196539 Enforce variable name for PortletPreferences

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the test failures? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Run a [generate-testray-csv](https://test-1-1.liferay.com/job/generate-testray-csv/6821/), the unique failure is a fluky issue.

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
