### PR TITLE
LPS-154238 SF, use isEmpty()

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
7.3.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/479

7.2.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/480

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
