### PR TITLE
LPS-164760 Make methods private in *ServiceImpl.java

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:reevaluate:1277401_5336

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help? Are the failures related to my changes?

**Comment by austinchiang** [comment]
ci:test:workflow

**Comment by austinchiang** [comment]
Hey @ling-alan-huang the failures from `ci:test:relevant` are known issues so it's not caused by your pull. I'm running the full workflow suite (ci:test:workflow) just to confirm other tests aren't affected

**Comment by ling-alan-huang** [comment]
Thanks @austinchiang

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/124578

**Pull request closed without merging**
