### PR TITLE
LPS-194212 remove unnecessary commons-collections dependency

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help scan the failures? Thanks.

**Comment by austinchiang** [comment]
Hey @ling-alan-huang @qz1010 can you please check this test failure? https://testray.liferay.com/home/-/testray/case_results/2412100964 It is only happening on this PR.

Everything else looks good

**Comment by qz1010** [comment]
spilt #2083 #2084

**Pull request closed without merging**
