### PR TITLE
LPS-204924 Move package, *TestUtil.java should be in test.util

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by Wa1ter-Shao** [comment]
Hi @ling-alan-huang ,

This pull will be rejected since [modules-semantic-versioning-jdk8](https://testray.liferay.com/home/-/testray/case_results/2483519977?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseTypeId%3D556778857%26testrayBuildId%3D2483518871%26testrayRunId%3D2483518888%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) issue

**Error message**:
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-entry-processor/fragment-entry-processor-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.entry.processor.helper        MINOR      7.0.0      7.0.0      7.1.0      VERSION INCREASE REQUIRED
     [exec]     	<   interface  com.liferay.fragment.entry.processor.helper.FragmentEntryProcessorHelper
     [exec]     		+   method     getMappedInfoItemFieldValue(com.liferay.portal.kernel.json.JSONObject,java.lang.String,com.liferay.info.item.InfoItemFieldValues,java.util.Locale)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.Object
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 9.4.0
```
Could you please take a look? Thank you.

**Comment by qz1010** [comment]
see #2396

**Pull request closed without merging**
