### PR TITLE
LPS-201261 Fix Import-Package in bnd.bnd

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:forword

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:stop

**Comment by qz1010** [comment]
ci:forword

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:forword

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the failures? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
