### PR TITLE
LPS-200296 Enforce name of class extending InitialRequestPortalInstanceLifecycleListener

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
```
java.lang.Exception: Found 8 formatting issues:
1: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/model/listener/PortalInstanceLifecycleListenerImpl.java (SourceCheck:JavaClassNameCheck)
2: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/main/java/com/liferay/content/dashboard/web/internal/instance/lifecycle/AddDefaultAssetVocabulariesPortalInstanceLifecycleListener.java (SourceCheck:JavaClassNameCheck)
3: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-shortcut/src/main/java/com/liferay/oauth2/provider/shortcut/internal/instance/lifecycle/AnalyticsCloudPortalInstanceLifecycleListener.java (SourceCheck:JavaClassNameCheck)
4: Library 'org.apache.zookeeper:zookeeper:3.4.14' contains known vulnerabilities(Authorization Bypass Through User-Controlled Key vulnerability in Apache ZooKeeper, https://github.com/advisories/GHSA-7286-pgfv-vxvh): /home/alan/liferay_code/master/liferay-portal/modules/apps/portal-search-solr8/portal-search-solr8-impl/build.gradle (SourceCheck:LibraryVulnerabilitiesCheck)
5: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/layout/prototype/AddLayoutPrototypePortalInstanceLifecycleListener.java (SourceCheck:JavaClassNameCheck)
6: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/internal/instance/lifecycle/KaleoPortalInstanceLifecycleListener.java (SourceCheck:JavaClassNameCheck)
7: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/apps/site/site-welcome-site-initializer/src/main/java/com/liferay/site/welcome/site/initializer/internal/instance/lifecycle/AddDefaultLayoutPortalInstanceLifecycleListener.java (SourceCheck:JavaClassNameCheck)
8: Name of class extending 'InitialRequestPortalInstanceLifecycleListener' should end with 'InitialRequestPortalInstanceLifecycleListener': /home/alan/liferay_code/master/liferay-portal/modules/dxp/apps/salesforce-connector/salesforce-connector/src/main/java/com/liferay/salesforce/connector/internal/instance/lifecycle/AddSalesforceConnectorPortalInstanceLifecycleListener.java (SourceCheck:JavaClassNameCheck)

```

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the failures? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
The failures not related to this pull request.

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
