### PR TITLE
LPS-196539 Renaming for PortletPreferences

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Passed. [ci:test:relevant](https://testray.liferay.com/en/home/-/testray/case_results/index?delta=100&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2439734023&testrayRunId=2439734062)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
