### PR TITLE
LPS-144606 Move SourceProcessor classes in the SF module into their own package

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-144606>

__Previous Pull Request:__
<https://github.com/ling-alan-huang/liferay-portal/pull/584>

__Notes:__
Fixed the errors from the previous pull request. I decided not to move the `ImportsFormatter` and `ImportsPackage` classes as it would require making a lot of changes that may be problematic. Also, I moved the unit tests for the source processors into their own package as well.

Let me know if you have any questions.

/cc: @hhuijser

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
I will have a look at it tomorrow.

**Comment by ling-alan-huang** [comment]
rebasing and resent: https://github.com/ling-alan-huang/liferay-portal/pull/594

**Pull request closed without merging**
