### PR TITLE
LPS-175368 Only enable on master for now

### PR DESCRIPTION
**Pull request by kevhlee**
This PR updates `JavaGetFeatureFlagCheck` so that it is only enabled on `master`. At the moment, `FeatureFlagManagerUtil` is not available in `7.x` branches, so this check should not enforced on the `7.x` .branches. The commits in this PR can be reverted in the future if [LPS-168928](https://issues.liferay.com/browse/LPS-168928) is backported to `7.3.x`.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
SF failure is not related to this PR. The fix is here https://github.com/brianchandotcom/liferay-portal/pull/134546

**Comment by ling-alan-huang** [comment]
@kevhlee Can you also enable it for SF tests in
https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/source-formatter.properties

Thanks.

**Comment by kevhlee** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/1840

**Pull request closed without merging**
