### PR TITLE
LPS-173386 Fix race condition and Windows-style path issue

### PR DESCRIPTION
**Pull request by kevhlee**
Ticket: [LPS-173386](https://issues.liferay.com/browse/LPS-173386)

Hi @ling-alan-huang and @qz1010. I decided to make some changes with how the SF check deals with paths. Rather than convert the logger names to filepaths, I think we should convert the filepaths to class/package names.

Let me know if there is a better way.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/130097

**Pull request closed without merging**
