### PR TITLE
LPS-156857 SF Remove unnecessary empty line

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward:enforce

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the failures? Thank you.

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
