### PR TITLE
LPS-193718 Revert "LPS-193718 Only enable for master, Alan will revert when all violations are fixed on other branches

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help scan the test failures? Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Sorry might have missed this. Checking...

**Comment by austinchiang** [comment]
Going to fix a wiki test since it's complaining about not being able to find a file

**Comment by austinchiang** [comment]
Testing in https://github.com/austinchiang/liferay-portal/pull/1499

**Pull request closed without merging**
