### PR TITLE
LPS-178978 The literal string goes second in Objects.equals call

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/132173

**Pull request closed without merging**
