### PR TITLE
LPS-183439 Rename *Configuration

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Hi @austinchiang Can you help check test failures? Thanks.

**Comment by WYZ-Issac** [comment]
Hi @ling-alan-huang , the backend test failure [com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadV...](https://testray.liferay.com/home/-/testray/case_results/2295927052?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2295921545%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) may be caused by your commit. Please have a look. Thank you.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
Hi @ling-alan-huang , the above failures are not related to your commit. I will forward it directly.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
#1851

**Comment by qz1010** [comment]
ci:close

**Pull request closed without merging**
