### PR TITLE
LPS-184431 Class *ConverterConstants should be in package ending with .converter.constants

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-184431

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Waiting for https://github.com/ling-alan-huang/liferay-portal/pull/1861 https://github.com/ling-alan-huang/liferay-portal/pull/1862 https://github.com/ling-alan-huang/liferay-portal/pull/1863 to be merged.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:foward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang And this PR, thanks.

**Comment by Hanlf** [comment]
The above failures in the latest ci:test:relevant job are not related this PR,

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
