### PR TITLE
LPS-204924 Add JavaModuleTestUtilCheck

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Splited into https://github.com/ling-alan-huang/liferay-portal/pull/2394 https://github.com/ling-alan-huang/liferay-portal/pull/2395 https://github.com/ling-alan-huang/liferay-portal/pull/2396 https://github.com/ling-alan-huang/liferay-portal/pull/2397

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/2404

**Pull request closed without merging**
