### PR TITLE
LPS-196539 Renaming for type PortletPreferences

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
Hi @qz1010,

Passed! [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2431222295). Can forward this pull request  Via `ci:forward:force`.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
Thanks @SylviaLuan

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/141458

**Pull request closed without merging**
