### PR TITLE
LPS-155484 Improve MVCCommandNameCheck to catch more cases

### PR DESCRIPTION
**Pull request by ling-alan-huang**
see: https://github.com/brianchandotcom/liferay-portal/pull/118316#issuecomment-1148083945

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:relevant:nocompile

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/118573

**Pull request closed without merging**
