### PR TITLE
LPS-123806_20201124_3_0

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@Tim-cao Can you have a look the failures? Thanks.
Actually, we hope this revert pull can resolve the failures, but it doesn't help.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
See https://github.com/ling-alan-huang/liferay-portal/pull/339

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
