### PR TITLE
LPS-169488 Rename attribute

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help us check the test failures? Thanks.

**Comment by austinchiang** [comment]
@ling-alan-huang test failures are unrelated

**Comment by ling-alan-huang** [comment]
Thanks Austin.
https://github.com/brianchandotcom/liferay-portal/pull/127918

**Pull request closed without merging**
