### PR TITLE
LPD-21972 Improve breaking change SF rule

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-21972

---

The purpose of this PR is to improve the SF rule that checks the breaking changes commit by including a new validation. The validation is that after `## Alternatives` `## What` and `## Why`, a line containing an explanation must exist.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
SF test failures are unrelated, I will fix it later.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
