### PR TITLE
LPS-203765 Move package, the package should have asset

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by austinchiang** [comment]
@ling-alan-huang failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
