### PR TITLE
LPS-202086 Remove elements in `*.batch-engine-data.json`

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
[@SylviaLuan](https://github.com/SylviaLuan) Can you help scan the test failures? Thanks.
/cc [@austinchiang](https://github.com/austinchiang)

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
