### PR TITLE
[SF] LPS-153297 Generate environment properties in system.properties

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-153297

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by W2jx** [comment]
Thank you @ling-alan-huang ,and could you change the prefix to SYSTEM for us?

**Pull request closed without merging**
