### PR TITLE
LPS-192251 Enforce using language key in clay:alert, instead of calling LanguageUtil

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help scan the failures? Thanks.

**Comment by austinchiang** [comment]
Failures unrelated @ling-alan-huang

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by qz1010** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/138897

**Pull request closed without merging**
