### PR TITLE
LPS-181280 Do not expose static components

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF issues:
https://issues.liferay.com/browse/LPS-181280
https://github.com/brianchandotcom/liferay-portal/pull/132538#issuecomment-1488775563

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the test failures? Thanks.

**Comment by austinchiang** [comment]
@ling-alan-huang there's a semver issue that might be related: https://testray.liferay.com/home/-/testray/case_results/2274801998 

`     [exec] > Task :core:petra:petra-http-invoker:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.petra.http.invoker                     MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.petra.http.invoker.HttpInvoker$HttpResponse
     [exec] 		+   method     getContentType()
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     setContentType(java.lang.String)
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 1.2.0`

besides that I think the other failures are irrelevant

**Comment by ling-alan-huang** [comment]
Thanks @austinchiang I am rebasing and will fix semer issue later.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
