### PR TITLE
LPS-176738 Remove SF rule for Liferay-Releng-Deprecated

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
Hi @ling-alan-huang , it seems the sf issues are not about my fix

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/131143

**Pull request closed without merging**
