### PR TITLE
LPS-153192 Enforce <#macro> tag style in FTL file

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
see: https://github.com/qz1010/liferay-portal/pull/22

**Pull request closed without merging**
