### PR TITLE
LPS-205017 Remove feature flag titles and descriptions from portal.properties

### PR DESCRIPTION
**Pull request by ling-alan-huang**
> This is an update for [LPS-205017](https://issues.liferay.com/browse/LPS-205017).
> 
> @ling-alan-huang feel free to alter my changes to the SF rule. The goal is that all `title` and `description` keys should _only_ live in `Language.properties`, but are still required for the `beta`, `release`, and `deprecation` statuses.
> 
> /cc @ethib137

/cc @drewbrokke

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by Wa1ter-Shao** [comment]
Passed review, failed cases are not related to this pull.
I think the risk of this pull is low, we can forward it directly.

/cc @SylviaLuan

**Comment by Wa1ter-Shao** [comment]
ci:forward:force

**Pull request closed without merging**
