### PR TITLE
LPS-202266 Avid changing the year in copyright when the file is not a new added file

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@ling-alan-huang I had to abort the `relevant` test because the process froze.

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/2278

**Pull request closed without merging**
