### PR TITLE
LPS-177111 Use assign and set call

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Can you help scan the test result? Thanks.

**Comment by SylviaLuan** [comment]
Passed! [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2438210419)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
