### PR TITLE
LPS-185667 SF, avoid stale object when calling (Local)Service(Util).update

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Hanlf Can you help check the test failures? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by Hanlf** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
Thanks @Hanlf

**Pull request closed without merging**
