### PR TITLE
LPS205913 Avoid chaining on getters

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the failures? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

There is a unique failure caused by this pull request.
[modules-semantic-versioning-jdk8](https://testray.liferay.com/home/-/testray/case_results/2530350760/)
```
[exec] > Task :apps:client-extension:client-extension-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.client.extension.constants             MINOR      2.6.0      2.6.0      2.7.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.client.extension.constants.ClientExtensionEntryConstants
     [exec] 		+   field      TYPE_COMMERCE_CHECKOUT_STEP
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   commerceCheckoutStep
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 11.3.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.client.extensi
```

**Pull request closed without merging**
