### PR TITLE
LPS-190915 Implement git process calls in SourceFormatterUtil

### PR DESCRIPTION
**Pull request by ling-alan-huang**
> From [drewbrokke](https://github.com/drewbrokke)

This is an update for [LPS-190915](https://issues.liferay.com/browse/LPS-190915).

Hi @ling-alan-huang! This pull is a first attempt at optimizing startup time for SourceFormatter. The ultimate goal is to have SF be usable in an editor context (for "format on save"). In order to accomplish this, we need to get SF as efficient as possible at processing one file.

I profiled SF and found that one of the most expensive operations was finding files and walking the file tree. The way I am improving that is by using `git ls-files`, which is very fast and can consume all the same filters passed into the `_scanForFiles` method. Surprisingly, `git ls-files` is often much faster than filtering an in-memory string list!

The are based off of a run of `gradlew formatSource` in `account-service`. 
Before: `37s`
After: `10s`

For these changes, we will see the most improvement when formatting small batches of files since the goal is to optimize startup time. We will see diminishing returns when processing lots of files since startup is a small portion of the overall cost.

There may be mistakes/oversights here, so I would really appreciate your feedback and any questions or concerns you may have.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@drewbrokke I updeated the PR to not breaking SF tests, and I think this way is safe to keep base dir as current dir when it is empty.
Also, the fileNames are all relative paths in old SF, let keep them as what they are before. Is it comforable for you to use the relative path in VSCode plugins?

**Comment by drewbrokke** [comment]
Hi @ling-alan-huang, I think that the changes are fine. As long as we hit the same number of target files, and that the output is usable by all callers, then I think it's good. Thank you!

**Pull request closed without merging**
