### PR TITLE
LPS-159932 Optional, Greedy reference should already be Dynamic

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant - Failed due to [Testray Outage](https://liferay.slack.com/archives/C19PWQ74J/p1660253108886939)

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/121737

**Pull request closed without merging**
