### PR TITLE
LPS-192251: Remove the use of  "LanguageUtil" in the clay alert messages and pass directly the key

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Please move logic to https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/JSPTagAttributesCheck.java#L96
and add a SF property to only enable for master for now.

**Comment by qz1010** [comment]
see #2032

**Pull request closed without merging**
