### PR TITLE
LPS-169281: Rename class that it extends BaseAutocompleteFDSFilter

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check `ci:test:relevant` failures? Thanks.

**Comment by austinchiang** [comment]
@ling-alan-huang test failures are either flaky or known https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2074779091. I'm not sure what the cause of [this SF issue is ](https://github.com/ling-alan-huang/liferay-portal/pull/1511#issuecomment-1325842971) but besides that LGTM

**Comment by ling-alan-huang** [comment]
Thanks @austinchiang The SF failures are not related to this pull.

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/126784

**Pull request closed without merging**
