### PR TITLE
LPD-45107 Fix com.liferay.source.formatter.processor.UpgradeCatchAllCheckTest under JDK17

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@ling-alan-huang I tested this fix locally with JDK17 and the unit test passed.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
