### PR TITLE
LPS-188912 Fix SF tests after copyright header change

### PR DESCRIPTION
**Pull request by kevhlee**
Tests in SF are failing because the expected line numbers were based on the old copyright header.

With these changes, `JavaSourceProcessor.testIncorrectCopyright` still fails. I was not sure how to handle this one, whether we should just remove it or if the test input needs to be changed.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/2022

**Comment by ling-alan-huang** [comment]
Thanks Kevin.

**Pull request closed without merging**
