### PR TITLE
LPS-205913 SF, avoid chaining on parameter to go over too many lines

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF issue:https://github.com/brianchandotcom/liferay-portal/commit/d3ac5a3afcfbb502b11a8366142575917f098983
SF message: Avoid chaining on parameter to go over too many lines. Create a new variable for better readability

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the failures? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
