### PR TITLE
LPS-177352 Add a new SF property to enable/disable formatting from JavaParser 

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://issues.liferay.com/browse/LPS-177352>

This pull request adds a new SF property for enabling/disabling formatting of Java and JSP files from `JavaParser`. By default, SF runs JavaParser to format Java/JSP code. However, it applies a specific Java code styling that users may not want (namely, customers and clients). Thus, users should be allowed to enable/disable JavaParser when executing SF.

Let me know if I need to add/remove/change anything.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@kevhlee I will be on PTO tomorrow, you can sent the pull request to Brian directly if the ci test are unrelated.

**Comment by kevhlee** [comment]
Forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/131671>

**Pull request closed without merging**
