### PR TITLE
LPS-204924 Move package, *TestUtil.java should be in test.util

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Run testray result: [#7662](https://test-1-1.liferay.com/job/generate-testray-csv/7662/)

**Comment by Wa1ter-Shao** [comment]
ci:test:relevant

**Comment by Wa1ter-Shao** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by Wa1ter-Shao** [comment]
Passed review, failed cases are not related to this pull.
I think the risk of this pull is low, we can forward it directly.

/cc @SylviaLuan

**Comment by Wa1ter-Shao** [comment]
ci:forward:force

**Comment by Wa1ter-Shao** [comment]
hi @ling-alan-huang ,

It seems there is something wrong when I forward this pull, could you please try to forward it? Thank you.

**Comment by ling-alan-huang** [comment]
Thanks @Wa1ter-Shao The changes are already in upstream, closing.

**Pull request closed without merging**
