### PR TITLE
LPS-192701 Enforce method and variable name for Expression and Unsafe*

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF request:
https://github.com/liferay/liferay-portal/commit/c71ae026ed51e53af1baccd5bed7126bb0c52186
https://github.com/liferay/liferay-portal/commit/19a29121182051a0393cf772b1452231faca81cc

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help scan the failures? Thanks.

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/139010

**Pull request closed without merging**
