### PR TITLE
Lps 127030

### PR DESCRIPTION
**Pull request by mtambara**
Hey @ling-alan-huang, a few things:
1. Can you check on this NPE in https://github.com/mtambara/liferay-portal/pull/1040#issuecomment-789340229?
2. I moved the test rule to `com.liferay.portal.test.rule`, can you change the SF rule to check for that?
3. Can you exclude unit tests in `portal-kernel`?
4. Because you're checking for the import statement, tests in the same package as `LiferayUnitTestRule` will fail the SF check even if the test rule is added (ex. `AspectJNewEnvJVMTestRuleTest`)

Thanks!

### CODE REVIEW

**Comment by mtambara** [comment]
Can you also exclude the `modules/test` directory?

**Comment by mtambara** [comment]
I also noticed that we're still skipping tests that import NewEnvTestRule and AspectJNewEnvTestRule, we don't have to do that anymore

**Comment by ling-alan-huang** [comment]
Got it.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/mtambara/liferay-portal/pull/1042

**Pull request closed without merging**
