### PR TITLE
LPS-171787 Fix the incorrect indentations in curl in Poshi Script

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Hi @austinchiang Are the test failures related to my changes?  Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @ling-alan-huang The functional failure is not related to this PR.

**Comment by ling-alan-huang** [comment]
Thanks @Hanlf see https://github.com/brianchandotcom/liferay-portal/pull/128532

**Pull request closed without merging**
