### PR TITLE
LPS-200296 Rename classes to be XyzInitialRequestPortalInstanceLifecycleListener

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help check the test results? Thanks.
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

Passed. [ci:test:relevant](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2451949178&testrayRunId=2451949237). You can forward this pr Via `ci:forward:force` after the tests finished.

**Comment by ling-alan-huang** [comment]
Thank you.

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/143186

**Pull request closed without merging**
