### PR TITLE
LPS-188912 Replace copyright year for *Exception.java

### PR DESCRIPTION
**Pull request by ling-alan-huang**
/cc @andrea-ale-sbarra This PR can fix SF issue in your [PR](https://github.com/liferay-commerce/liferay-portal/pull/4149).

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the failures? Thanks.

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
