### PR TITLE
LPS-195894 SF, use Objects.equals on method

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the failures? Thanks.
/cc @austinchiang

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

There are two cases failed by this pull request.
[com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest
](https://testray.liferay.com/home/-/testray/case_results/2424407906)
```
[beanshell] 2023-09-14 16:43:38.968 INFO  [com.liferay.site.initializer.extender.test-executor-thread][BundleStartStopLogger:71] STOPPED com.liferay.site.initializer.extender.test.bundle.1_1.0.0 [1553]
[beanshell] 2023-09-14 16:43:39.052 INFO  [com.liferay.site.initializer.extender.test-executor-thread][BundleStartStopLogger:71] STOPPED com.liferay.site.initializer.extender.test.bundle.2_1.0.0 [1554]
     [exec] 
     [exec] com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest > testInitializeFromBundle FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.exception.NoSuchUserGroupException: No UserGroup exists with the primary key 34352
     [exec]     	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.getBaseModels(TableMapperImpl.java:456)
     [exec]     	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.getLeftBaseModels(TableMapperImpl.java:311)
     [exec]     	at com.liferay.portal.kernel.internal.service.persistence.change.tracking.CTTableMapper.getLeftBaseModels(CTTableMapper.java:247)
     [exec]     	at com.liferay.portal.kernel.internal.service.persistence.ReverseTableMapper.getRightBaseModels(ReverseTableMapper.java:118)
     [exec]     	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.getUserGroups(UserPersistenceImpl.java:10712)
     [exec]     	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.getUserGroups(UserPersistenceImpl.java:10690)
     [exec]     	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.getUserGroups(UserPersistenceImpl.java:10671)
     [exec]     	at com.liferay.portal.service.base.UserGroupLocalServiceBaseImpl.getUserUserGroups(UserGroupLocalServiceBaseImpl.java:846)
     [exec]     	at sun.reflect.GeneratedMethodAccessor3266.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
[modules-semantic-versioning-jdk8
](https://testray.liferay.com/home/-/testray/case_results/2424407904)
```
 [exec] > Task :apps:object:object-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.object.exception                       MINOR      22.0.0     22.0.0     22.1.0     VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.object.exception.ObjectEntryStatusException
     [exec] 		+   extends    com.liferay.portal.kernel.exception.PortalException
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     <init>(java.lang.String)
     [exec] 			+   return     void
     [exec] 		+   method     <init>(java.lang.String,java.lang.Throwable)
     [exec] 			+   return     void
     [exec] 		+   method     <init>(java.lang.Throwable)
     [exec] 			+   return     void
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
```

**Comment by ling-alan-huang** [comment]
So, this PR caused the failures, right?

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
I have to splitted the PR into https://github.com/ling-alan-huang/liferay-portal/pull/2131 and https://github.com/ling-alan-huang/liferay-portal/pull/2132

**Comment by ling-alan-huang** [comment]
@SylviaLuan I don't understand why my changes can cause the failures.
Because even I removed an empty line in https://github.com/ling-alan-huang/liferay-portal/pull/2137, we still have the same failure.

Let me know if I can use `ci:forward:force` this PR.

**Comment by SylviaLuan** [comment]
Thanks @ling-alan-huang,

For [com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest](https://testray.liferay.com/home/-/testray/case_results/2424407906) can see this [history](https://testray.liferay.com/home/-/testray/cases/1552444941/view?p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc&testrayFactorOptionName=mysql), only failed on https://github.com/ling-alan-huang/liferay-portal/pull/2127 and https://github.com/ling-alan-huang/liferay-portal/pull/2137.
And for [modules-semantic-versioning-jdk8](https://testray.liferay.com/home/-/testray/case_results/2424407904) since the failed class is `com.liferay.object.exception.ObjectEntryStatusException` and the pull request has the commits about object. So is caused by this pull request.

**Comment by SylviaLuan** [comment]
For [com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest](https://testray.liferay.com/home/-/testray/case_results/2424407906) can see this [history](https://testray.liferay.com/home/-/testray/cases/1552444941/view?p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc&testrayFactorOptionName=mysql), only failed on [#2127](https://github.com/ling-alan-huang/liferay-portal/pull/2127) and [#2137](https://github.com/ling-alan-huang/liferay-portal/pull/2137) recently.
And for [modules-semantic-versioning-jdk8](https://testray.liferay.com/home/-/testray/case_results/2424407904) since the failed class is com.liferay.object.exception.ObjectEntryStatusException and the pull request has the commits about the object. So is caused by this pull request.

**Comment by ling-alan-huang** [comment]
@SylviaLuan But in https://github.com/ling-alan-huang/liferay-portal/pull/2137, I just removed an empty line only.
I don't understand why removing an empty line can cause relevent failures.
Do we have other ways to check this PR?

**Comment by austinchiang** [comment]
@SylviaLuan might be a flaky test, rerun to make sure

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

This case still failed: [com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest](https://testray.liferay.com/home/-/testray/case_results/2424407906)
And I fetched your code and pushed to myself: [#32](https://github.com/SylviaLuan/liferay-portal/pull/32) and the case passed on my pull. I don't know why the case always failed on your pull. But you can forward this pull now.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
