### PR TITLE
LPS-161903 GradleBuildFileVisitor should support handlling buildScrip…

### PR DESCRIPTION
**Pull request by Seiphon**
…t dependencies

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see https://github.com/Seiphon/liferay-portal/pull/41

**Pull request closed without merging**
