### PR TITLE
LPS-144888 Use isSet() to check whether a variable was set, instead of an old pattern by using contains()

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-144888

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
_Related pulls:_
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/36293
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/36294
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/36295
7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/36296

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@ling-alan-huang SF failure is unrelated, fix here (last commit): https://github.com/hhuijser/liferay-portal/pull/6156

**Comment by ling-alan-huang** [comment]
Got it.

**Comment by ling-alan-huang** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/111860

**Pull request closed without merging**
