### PR TITLE
LPS-32865 Do not use Google fonts

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Hi @jkappler Do you know which team can help fix the SF violations? We need to fix or exclude them before pushing the SF rule.
Thanks.

**Comment by ling-alan-huang** [comment]
```
     [java] java.lang.Exception: Found 15 formatting issues:
     [java] 1: Do not use Google fonts: ./modules/dxp/apps/osb/osb-faro/osb-faro-theme/src/templates/portal_normal.ftl 12 (SourceCheck:GoogleFontsCheck)
     [java] 2: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-approved-organization-template/en-US.html 10 (SourceCheck:GoogleFontsCheck)
     [java] 3: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-approved-organization-template/en-US.html 12 (SourceCheck:GoogleFontsCheck)
     [java] 4: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-approved-request-template/en-US.html 10 (SourceCheck:GoogleFontsCheck)
     [java] 5: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-approved-request-template/en-US.html 12 (SourceCheck:GoogleFontsCheck)
     [java] 6: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-more-information-organization-template/en-US.html 10 (SourceCheck:GoogleFontsCheck)
     [java] 7: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-more-information-organization-template/en-US.html 12 (SourceCheck:GoogleFontsCheck)
     [java] 8: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-more-information-request-template/en-US.html 10 (SourceCheck:GoogleFontsCheck)
     [java] 9: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-more-information-request-template/en-US.html 12 (SourceCheck:GoogleFontsCheck)
     [java] 10: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-rejected-organization-template/en-US.html 10 (SourceCheck:GoogleFontsCheck)
     [java] 11: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-rejected-organization-template/en-US.html 12 (SourceCheck:GoogleFontsCheck)
     [java] 12: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-rejected-request-template/en-US.html 10 (SourceCheck:GoogleFontsCheck)
     [java] 13: Do not use Google fonts: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/notification-templates/evp-rejected-request-template/en-US.html 12 (SourceCheck:GoogleFontsCheck)
     [java] 14: Do not use Google fonts: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/index.html 8 (SourceCheck:GoogleFontsCheck)
     [java] 15: Do not use Google fonts: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/index.html 11 (SourceCheck:GoogleFontsCheck)

```

**Comment by jkappler** [comment]
Hi @ling-alan-huang, first, thanks for this!

For faro, I think it's Analytics Cloud Team
For evp site initializer Content Solutions Team
For liferay-marketplace-workspace I'm unsure, since it was added in a ISSITES project

**Comment by ling-alan-huang** [comment]
Thanks @jkappler 
I don't know anyone in those teams, can you help ping them here if you know them in teams?

/cc @drewbrokke

**Comment by jkappler** [comment]
Hi @ling-alan-huang, I already contacted the analytics team, and some people to see if they can help us out

**Comment by ling-alan-huang** [comment]
Thank you so much. @jkappler

**Comment by ling-alan-huang** [comment]
see https://github.com/liferay-devtools/liferay-portal/pull/166

**Pull request closed without merging**
