### PR TITLE
Revert "LPS-193718 Only enable for master, Alan will revert when all …

### PR DESCRIPTION
**Pull request by ling-alan-huang**
…violations are fixed on other branches"

This reverts commit 1dbc8d0ce0ed0163a875d130d48c248bce66fe2a.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Hi @austinchiang
Can you help fix one SF issue:

`Test dependencies file '/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/Document_2.mp3' is only referenced by one module, move it to module dependencies directory: /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/wiki/WikiPage.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)`

`Document_2.mp3` were used in 2 places:

1.
https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/wiki/WikiPage.testcase

2.
https://github.com/liferay/liferay-portal/commit/1eb27ab01eb14c8674852c01666b3e6974d3cc97
(You alreay removed)

Can you help move it to the proper direcotry? Thanks.

**Comment by austinchiang** [comment]
Checking now

**Comment by austinchiang** [comment]
ci:close

**Pull request closed without merging**
