### PR TITLE
LPS-174305 Support specified directory to execute lang-sanitizer tool

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
ci:reevaluate:1357401_3489

**Comment by ling-alan-huang** [comment]
@Seiphon I added logic to sort messages, see https://github.com/Seiphon/liferay-portal/pull/60

**Pull request closed without merging**
