### PR TITLE
LPS-177111 Use set call with inlined if-statement

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help scan the test failures? Thanks.

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

This pull request has a unique issue.
[com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionVulcanBatchEngineTaskItemDelegateTest
](https://testray.liferay.com/home/-/testray/case_results/2420945923)
```
beanshell] 2023-09-08 10:53:57.264 INFO  [com.liferay.object.admin.rest.test-executor-thread][BundleSiteInitializer:622] Initialized com.liferay.site.initializer.welcome for group 36706 in 856 ms
     [exec] 
     [exec] com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionVulcanBatchEngineTaskItemDelegateTest > testCreate FAILED
     [exec]     java.lang.UnsupportedOperationException
     [exec]     	at com.liferay.object.admin.rest.internal.resource.v1_0.ObjectDefinitionResourceImpl.postObjectDefinition(ObjectDefinitionResourceImpl.java:241)
     [exec]     	at com.liferay.object.admin.rest.internal.resource.v1_0.BaseObjectDefinitionResourceImpl.lambda$create$0(BaseObjectDefinitionResourceImpl.java:733)
     [exec]     	at com.liferay.object.admin.rest.internal.resource.v1_0.BaseObjectDefinitionResourceImpl.create(BaseObjectDefinitionResourceImpl.java:791)
     [exec]     	at com.liferay.object.admin.rest.internal.resource.v1_0.ObjectDefinitionResourceImpl.create(ObjectDefinitionResourceImpl.java:116)
     [exec]     	at com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionVulcanBatchEngineTaskItemDelegateTest.testCreate(ObjectDefinitionVulcanBatchEngineTaskItemDelegateTest.java:147)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
[beanshell] 2023-09-08 10:54:16.258 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:71] STOPPED com.liferay.object.admin.rest.test_1.0.0 [1547]
```

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan I updated the code, can you help check the failures again? Thanks.

**Comment by SylviaLuan** [comment]
The failure tests are not related to this pull request.
[ci:test:relevant](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2422277731&testrayRunId=2422277790)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/140596

**Pull request closed without merging**
