### PR TITLE
LPS-190915 Avoid _sfIgnoreDirectories and _subrepoIgnoreDirector can not take effect properly

### PR DESCRIPTION
**Pull request by qz1010**
…ies cannot take effect properly

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
--Base CETSourceProcessor logic, we make a demo for test.
	
	public class ProcessTest {

		public static void main(String[] args) {
			List<String> a = Arrays.asList("git", "ls-files", "--full-name", "--", ":(glob)**/*CET.java", ":(exclude,glob)/home/liferay/repo/liferay-portal/modules/third-party/com-google-ical/src/main");
			ProcessBuilder processBuilder = new ProcessBuilder(a);
		
			processBuilder.directory(new File("/home/liferay/repo/liferay-portal/modules/apps/client-extension/client-extension-type-api/src/main/java/com/liferay/client/extension/type"));
		
			try {
				Process process = processBuilder.start();
		
				Scanner scanner = new Scanner(process.getInputStream());
		
		
				while (scanner.hasNext()) {
				System.out.println(scanner.next());
				}
		
				scanner.close();
			}
			catch (IOException ioException) {
				throw new RuntimeException(ioException);
			}
		}
	}

processBuilder.directory and exclude path both use full path, linux can return result sucessfuly, but window can't

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/2094

**Comment by qz1010** [comment]
see #2276

**Pull request closed without merging**
