### PR TITLE
LPS-156857: Remove unnecessary empty line in continuous set method | 3

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@hanlf Can you help scan the failures? Thanks.
/cc @austinchiang

**Comment by Hanlf** [comment]
Hi@ling-alan-huang  and @qz1010 The failure should be related to the PR, go to any apps under the site admin, the portal UI is broken, could you please take a look? 

UI

**Comment by ling-alan-huang** [comment]
Thanks @Hanlf

**Pull request closed without merging**
