### PR TITLE
LPS-175154 Move logic to checkstyle, because SF is not smart enough to do typecast

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the test failures? Just ci:test:relevat failures. Thanks.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
@ling-alan-huang The latest ci:test:relevant failures are not related to this PR.

**Comment by ling-alan-huang** [comment]
Thank @Hanlf 
Sent to Brian for review https://github.com/brianchandotcom/liferay-portal/pull/130538

**Pull request closed without merging**
