### PR TITLE
LPS-182475: Remove unnecessary toString() in com.liferay.petra.string.StringBundler.concat | 1

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
ci:forward

**Comment by qz1010** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Hi @austinchiang Please help check the test, thanks.
https://github.com/ling-alan-huang/liferay-portal/pull/1855 https://github.com/ling-alan-huang/liferay-portal/pull/1856 https://github.com/ling-alan-huang/liferay-portal/pull/1857

**Comment by austinchiang** [comment]
Will check tomorrow

**Comment by austinchiang** [comment]
test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
