### PR TITLE
LPS-182623 `SourceProcessor` is not available in `JavaTermCheck` check

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://issues.liferay.com/browse/LPS-182623>

This pull request makes it so that `JavaTermCheck` can access their respective `SourceProcessor` objects. At the moment, calling `JavaTermCheck.getSourceProcessor()` returns a `null` value.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hey @kevhlee Can we just call `getSourceProcessor()` to get SourceProcessor from

https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/BaseSourceCheck.java#L602-L604

**Comment by kevhlee** [comment]
@ling-alan-huang, that's the issue though. Calling methods `null` because `setSourceProcessor()` is not called for `BaseJavaTermCheck`.

**Comment by kevhlee** [comment]
@ling-alan-huang, should I be addressing this issue in another part of the SF code?

**Comment by ling-alan-huang** [comment]
Oh, I see, let me look into it.

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
