### PR TITLE
LPS-190915 Implement git process calls in SourceFormatterUtil

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-190915](https://issues.liferay.com/browse/LPS-190915).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@ling-alan-huang I think those SF failures are not unique to this pull, but feel free to double-check.

**Comment by ling-alan-huang** [comment]
I will have a look later today.

**Comment by drewbrokke** [comment]
Thanks @ling-alan-huang. Regarding https://github.com/ling-alan-huang/liferay-portal/pull/2018/commits/35bb0aedc6ba67cbd4b5c4d02864280c36c0e44a, When I tried to use SF standalone, it couldn't find a bunch of classes. I'm not exactly sure how this works, but it seems like some transitive dependencies are not present in that fat jar. I'm not 100% sure, but we might need to update our build script for standalone to include those if Brian will not allow us to include them explicitly.

**Comment by ling-alan-huang** [comment]
I am not sure how often he build the fat jar or maybe he has some other script to do it.
Let's check with Brian when this fix get merged.

**Pull request closed without merging**
