### PR TITLE
LPD-20503 Add SF suppression

### PR DESCRIPTION
**Pull request by ling-alan-huang**
/cc @jeffwu0724

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by jeffwu0724** [comment]
@ling-alan-huang Thanks a lot!

**Pull request closed without merging**
