### PR TITLE
LPS-202762 Enforce an empty line between two <link>, since it does order matters

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF issue: https://github.com/brianchandotcom/liferay-portal/commit/6defd2511c3f9054acdebd42fcdaa742045c3c6a

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
