### PR TITLE
LPS-186832 Update the help text for formatSource task

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @ling-alan-huang and @lawrence-lee, this is the help text display, if it need to adjust, please let me know

Screenshot 2023-09-18 152613

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@Seiphon , why is `task.name` a parameter? 

cc @drewbrokke

**Comment by Seiphon** [comment]
> @Seiphon , why is `task.name` a parameter? 
> 
> 
> 
> cc @drewbrokke 

Because the formatSource and formatSourceUpgrade task both can use these system properties, so I make the 'task.name' a parameter

**Comment by drewbrokke** [comment]
Hey @Seiphon, thank you for sending this, but I think there is more discussion required about the desired outcome with this one. I'll try to put my thoughts together this week, but I don't think this ticket is quite ready for dev yet.

**Comment by Seiphon** [comment]
@drewbrokke OK，thank you！

**Pull request closed without merging**
