### PR TITLE
LPS-198462 Remove nonexistent package

### PR DESCRIPTION
**Pull request by ling-alan-huang**
see 87a3c8bf38374f1987debdcedaed7f9e7a0dfdbc

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Can you help scan the failures? Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
