### PR TITLE
LPS-174314 Auto SF, use passed in variable

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the test failures. Thank you.

**Comment by austinchiang** [comment]
@ling-alan-huang I'm not sure if the failure in [testGetKnowledgeBaseFolderKnowledgeBaseArticlesPageWithSortDateTime ](https://testray.liferay.com/reports/production/logs/2023-03/test-1-33/test-portal-acceptance-pullrequest(master)/2950/modules-integration-mysql57-jdk8/2/2/jenkins-console.txt.gz?authuser=0) is related to the pull. Can you please check it? If you don't think it is then it should be safe to forward (the rest of the failures are known issues)

**Comment by ling-alan-huang** [comment]
@qz1010 Please help me check the changes again.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Pull request closed without merging**
