### PR TITLE
LPS-190915 Improve performance in SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@qz1010 see [fc30dcb](https://github.com/ling-alan-huang/liferay-portal/pull/2318/commits/fc30dcbd2220539ce2e1228d391feac13a00a04c)

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
