### PR TITLE
LPS-160079 Check unused @Reference private variable

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@JanisZhang @dantewang see ci:test:sf result.

**Comment by dantewang** [comment]
@JanisZhang I think we only cleaned up part of account? Could you double check so that we can have a whitelist item?

**Comment by JanisZhang** [comment]
@dantewang sorry, I missed some fields in the account which are used to declare dependency. 
cc/ @ling-alan-huang

**Comment by dantewang** [comment]
@JanisZhang Oh, OK. We know clearly that those fields are declaring dependencies. So the plan for those is to make them "used". @ling-alan-huang Let's change to another path in the whitelist, you can see what Janis sent on Slack.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@dantewang @JanisZhang Please keep maintaining SF properties when this PR is merged

https://github.com/ling-alan-huang/liferay-portal/pull/1394/files#diff-967a46bafa2036c78c2d3c5c2ad04e624b891d7821d882f38564650ca3131f98R334-R345

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
