### PR TITLE
LPS-177111 SF, use set calls

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Can you help scan the test? Thanks.

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Passed [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2427677995)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
This PR will have conflicts when I manually send to BChan, I keep this PR open, and will resend later.

**Pull request closed without merging**
