### PR TITLE
LPS-144124 LRQA-72463

### PR DESCRIPTION
**Pull request by vicnate5**
@ling-alan-huang This is ready to go on the Poshi side, there is still some changes in the SF modules when I run format source, could you take a look? This can be forwarded to BChan when you are ready

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
I will have a look..

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
see: https://github.com/ling-alan-huang/liferay-portal/pull/628

**Pull request closed without merging**
