### PR TITLE
LPS-174314 Auto SF, use passed in variable

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @qz1010 and @ling-alan-huang, all failures are unrelated to this PR. You could manual forward this one to Brian.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
