### PR TITLE
LPS-105380 Clean up SF suppressions

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:help

**Comment by ling-alan-huang** [comment]
ci:test:gradle-plugins

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Can you help check the test failures? Thanks.

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

[ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2487847991) Passed.
No result on this suit [ci:test:gradle-plugins](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2487909959).

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
