### PR TITLE
LPS-189971 `JavaClassParser.parseJavaClass()` cannot handle different types of newlines

### PR DESCRIPTION
**Pull request by kevhlee**
Hi @ling-alan-huang! It looks like `JavaClassParser` is not able parse Java files that contain newline escape characters like `\r\n`. It will be greatly appreciated if you could take a look at this.

Thanks in advance!

From @michaelmdelcavalcanti:

>During the upgrade of the chile bank, when we ran the automation we realized that it was not being executed correctly, when investigating the error we found that some of the client files were with the \r\n as a line break instead of the standard \n, the error was occurring when counting the comment lines in the JavaClassParser file, this PR is about an adjustment in the JavaClassParser file so that this does not occur again.
I look forward to your review and opinion.
>
>Ticket: [LPS-189871](https://liferay.atlassian.net/browse/LPS-189871)
>
>Note: This same problem is happening with UpgradeBNDIncludeResourceCheck and BNDSourceUtil, a fix is being developed.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@kevhlee Can we change the line breaks from `\r\n` to `\n` before upgrading checks?
After all upgrading checks we can change the line breaks back to `\r\n`.

**Comment by kevhlee** [comment]
Hi @ling-alan-huang, we could do that. But can you share why you think converting `\r\n` in the files for upgrade checks is better than just checking for the `\r\n` in `JavaClassParser`.

**Comment by ling-alan-huang** [comment]
Hi @kevhlee, I just found we are doing this here: https://github.com/kevhlee/liferay-portal/blob/LPS-189971/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/processor/BaseSourceProcessor.java#L305

**Comment by kevhlee** [comment]
Hi @ling-alan-huang, sorry for the late response. For now, we will go with your suggestion.

**Pull request closed without merging**
