### PR TITLE
LPS-192251 Enforce using language key in clay:alert, instead of calling LanguageUtil

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
case 1:		message='<%= LanguageUtil.get(request, (abc ? "aaa" : "bbb")) + "ccc" %>'
case 2:		message='<%= LanguageUtil.get(request, abc) %>'

@qz1010

**Comment by qz1010** [comment]
see #2035

**Pull request closed without merging**
