### PR TITLE
LPS-151643 Add missing line break for curly braces

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
see: https://github.com/Seiphon/liferay-portal/pull/20

**Pull request closed without merging**
