### PR TITLE
LPS-191331 Use fully qualified class name

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang

**Comment by Jeremy-Ch** [comment]
Hi @ling-alan-huang The failures are unrelated to this pr. You can forward it directly. Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
