### PR TITLE
LPS-204924 Move package, *TestUtil.java should be in test.util

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Can you help scan the test failures from PRs below? Thanks.
/cc @austinchiang

https://github.com/ling-alan-huang/liferay-portal/pull/2394 https://github.com/ling-alan-huang/liferay-portal/pull/2395 https://github.com/ling-alan-huang/liferay-portal/pull/2396 https://github.com/ling-alan-huang/liferay-portal/pull/2397

**Comment by SylviaLuan** [comment]
Run a testray result here:[#7661]( https://test-1-1.liferay.com/job/generate-testray-csv/7661/)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
