### PR TITLE
LPS-150272 Check for vulnerable libraries in Source Formatter

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
[com.liferay.headless.delivery.resource.v1_0.test.BlogPostingResourceTest](https://testray.liferay.com/home/-/testray/case_results/2265078895?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2265077740%26testrayRunId%3D2265077805%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) and [com.liferay.headless.delivery.resource.v1_0.test.DocumentResourceTest](https://testray.liferay.com/home/-/testray/case_results/2265079004?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2265077740%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failures are both unique to this pull, but they don't look related to your changes so they're probably flukes. PR LGTM

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/133193

**Pull request closed without merging**
