### PR TITLE
LPS-196539 Enforce variable name for PortletPreferences

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan Why ci still didn't give us the test results?
/cc @austinchiang

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang,

I have ask this issue on ci slack channel. Please see [here](https://liferay.slack.com/archives/CL3TWSMHQ/p1698021638677249).

**Comment by ling-alan-huang** [comment]
Thank you @SylviaLuan

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by qz1010** [comment]
split #2262 #2263 #2264

**Comment by qz1010** [comment]
ci:close

**Pull request closed without merging**
