### PR TITLE
LPS-190915 Implement git process calls in SourceFormatterUtil

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-190915](https://issues.liferay.com/browse/LPS-190915).

Hi @ling-alan-huang! This pull is a first attempt at optimizing startup time for SourceFormatter. The ultimate goal is to have SF be usable in an editor context (for "format on save"). In order to accomplish this, we need to get SF as efficient as possible at processing one file.

I profiled SF and found that one of the most expensive operations was finding files and walking the file tree. The way I am improving that is by using `git ls-files`, which is very fast and can consume all the same filters passed into the `_scanForFiles` method. Surprisingly, `git ls-files` is often much faster than filtering an in-memory string list!

Additionally, I updated a couple of hotspots in individual checks as an example of how it can be used. Again, the profiler showed improvement. I will attach the before-and-after profiles to the Jira ticket if you would like to inspect them.

The are based off of a run of `gradlew formatSource` in `account-service`. 
Before: `37s`
After: `10s`

For these changes, we will see the most improvement when formatting small batches of files since the goal is to optimize startup time. We will see diminishing returns when processing lots of files since startup is a small portion of the overall cost.

There may be mistakes/oversights here, so I would really appreciate your feedback and any questions or concerns you may have.

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @lawrence-lee

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@ling-alan-huang I just pushed a fix for the archive files being checked, and removed the extra usages. I figure we can start with just the scan for files improvement, then build from there.

**Comment by ling-alan-huang** [comment]
@drewbrokke You rock! Please see https://github.com/drewbrokke/liferay-portal/pull/1469

**Pull request closed without merging**
