### PR TITLE
LPS-150272 Skip LibraryVulnerabilitiesCheck check when we have internet problem, we only do the SF check when token is available.

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Skip LibraryVulnerabilitiesCheck check when we have internet problem, we only do the SF check when token is available.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the test failures, thanks.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
