### PR TITLE
LPS-190915 Avoid to break gw gradleTest from /sdk/gradle-plugins-source-formatter

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Jeremy-Ch Can you help scan the failures? Thanks.
/cc @austinchiang

**Comment by Jeremy-Ch** [comment]
Hi @ling-alan-huang The failures are unrelated. Thanks.

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Jeremy-Ch Thank you.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
