### PR TITLE
LPS-152539 Fix missing language key

### PR DESCRIPTION
**Pull request by ling-alan-huang**
see: [64e55b62706bb7d07c932bfb433c0d18d02b6b0e](https://github.com/liferay/liferay-portal/commit/64e55b62706bb7d07c932bfb433c0d18d02b6b0e)

SF issue:
```
java.lang.Exception: Found 3 formatting issues:
1: Missing language key 'to-enable-segmentation-go-to-system-settings-segments-segments-service': /home/alan/liferay_code/master/liferay-portal/modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry.jsp (SourceCheck:JSPLanguageKeysCheck)
2: Missing language key 'to-enable-segmentation-go-to-system-settings-segments-segments-service': /home/alan/liferay_code/master/liferay-portal/modules/apps/segments/segments-simulation-web/src/main/resources/META-INF/resources/view.jsp (SourceCheck:JSPLanguageKeysCheck)
3: Missing language key 'to-enable-segmentation-go-to-system-settings-segments-segments-service': /home/alan/liferay_code/master/liferay-portal/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/view.jsp (SourceCheck:JSPLanguageKeysCheck)
```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Thanks a lot @ling-alan-huang !!

The failing tests look unrelated, so I will write ci:forward.

Thanks!!

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
