### PR TITLE
formatXML results

### PR DESCRIPTION
**Pull request by ling-alan-huang**
**THIS IS NOT A REAL PULL REQUEST.**

Run task `formatXML`:
```
alan@alan-5540:~/liferay_code/master/liferay-portal/modules/apps/account/account-service[LPS-formatXML-task]$ ../../../../gradlew :apps:account:account-service:formatXML
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Listening for transport dt_socket at address: 6006
Configuration on demand is an incubating feature.

> Task :apps:account:account-service:formatXML
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en

BUILD SUCCESSFUL in 13s
1 actionable task: 1 executed

alan@alan-5540:~/liferay_code/master/liferay-portal/modules/apps/account/account-service[LPS-formatXML-task]$ git status
On branch LPS-formatXML-task
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/main/resources/META-INF/module-hbm.xml
	modified:   src/main/resources/META-INF/portlet-model-hints.xml

```

Hi @hhuijser,
Looks like task `formatXML` - [FormatXMLTask.java](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-xml-formatter/src/main/java/com/liferay/gradle/plugins/xml/formatter/FormatXMLTask.java) is calling [XMLFormatter.java](https://github.com/liferay/liferay-portal/blob/master/modules/util/xml-formatter/src/main/java/com/liferay/xml/formatter/XMLFormatter.java#L60).

And [Dom4jUtil.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/petra/petra-xml/src/main/java/com/liferay/petra/xml/Dom4jUtil.java#L74) will use `xmlWriter.write(node);` to recreate the file.

After having a look at the changes of those two files by `formatXML`, I found that there are also some attributes were added.

SF under `modules` doesn't use `XMLFormatter.java`,  I don't understand why we have different SF rules for xml from `formatXML` and `sourceFormat`.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@ling-alan-huang, looks like `XMLFormatter` hasn't really been changed for like 10 years and I got a feeling SF is doing everything we need. Can you look into this and integrate whatever logic we have in `XMLFormatter` and move to SF. After that I think we should be able to get rid of `XMLFormatter`

**Comment by ling-alan-huang** [comment]
@hhuijser, got it, I will do it later.

**Comment by ling-alan-huang** [comment]
Closing, open two tasks to track this issue.

https://issues.liferay.com/browse/LPS-101108
https://issues.liferay.com/browse/LPS-101026

**Pull request closed without merging**
