### PR TITLE
LPS-156857 Remove unnecessary empty line

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
No rush, and this one, thanks @austinchiang

**Comment by austinchiang** [comment]
Hey @ling-alan-huang can you check if [this failure](https://testray.liferay.com/home/-/testray/case_results/2362063204?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2362056898%26testrayRunId%3D2362056919%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) might be related? Based on the logs I don't think so but this failure is only happening on this PR every time relevant was run.

Everything else LGTM

**Comment by ling-alan-huang** [comment]
@austinchiang Thank you, I will check it again later.

**Comment by ling-alan-huang** [comment]
ci:foward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Splitted PRs: https://github.com/ling-alan-huang/liferay-portal/pull/1987 https://github.com/ling-alan-huang/liferay-portal/pull/1986 https://github.com/ling-alan-huang/liferay-portal/pull/1985 https://github.com/ling-alan-huang/liferay-portal/pull/1984 https://github.com/ling-alan-huang/liferay-portal/pull/1983

**Pull request closed without merging**
