### PR TITLE
LPS-197542 SF, avoid chaining on Type Cast

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF issue: https://github.com/liferay/liferay-portal/commit/b5d6a2bff9f8ec10ff36b6539f132fcdcf6f683a

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
splitted pulls: https://github.com/ling-alan-huang/liferay-portal/pull/2180, https://github.com/ling-alan-huang/liferay-portal/pull/2181, https://github.com/ling-alan-huang/liferay-portal/pull/2182

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Passed! [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2438092080)

**Comment by SylviaLuan** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
Thanks @SylviaLuan

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/141987

**Pull request closed without merging**
