### PR TITLE
LPS-179838 Simplify `new Problem` instantiation parameters

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-179838

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Hi @austinchiang Are the failures relate to my this PR? Thanks.

**Comment by austinchiang** [comment]
@ling-alan-huang not related

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Thanks @austinchiang Let me fix new coming SF issues today.

**Comment by ling-alan-huang** [comment]
I sent SF fix here: https://github.com/ling-alan-huang/liferay-portal/pull/1800

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
