### PR TITLE
LPS-192701 Enforce method and variable name for PrintWriter

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by qz1010** [comment]
resend from [brianchandotcom#139047](https://github.com/brianchandotcom/liferay-portal/pull/139047)

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/139129

**Pull request closed without merging**
