### PR TITLE
LPS-147690 Add echo message check for Source Format

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@Seiphon Think about this case: `<echo level="error" message="error" /><echo level="info" message="info" />`

**Comment by Seiphon** [comment]
Hi @ling-alan-huang , I have updated this pr to accurate the regular expression. please help to review again.

**Comment by ling-alan-huang** [comment]
see: https://github.com/Seiphon/liferay-portal/pull/14

**Pull request closed without merging**
