### PR TITLE
LPS-179838: Simply Java "Problem" parameter

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by qz1010** [comment]
ci:test:sf

**Comment by qz1010** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Sent Auto SF here: https://github.com/ling-alan-huang/liferay-portal/pull/1760

**Comment by ling-alan-huang** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/1797

**Pull request closed without merging**
