### PR TITLE
LPS-168901 fix SF issue

### PR DESCRIPTION
**Pull request by simonjhy**
I fixed the other issuesexcept the plugins applied issue. we can not change the sequence of apply plugin: "net.saliman.properties" and apply plugin: "com.liferay.workspace", this will cause gradle workspace plugin can not load the properties defined in gradle-local.properties.

### CODE REVIEW

**Comment by simonjhy** [comment]
@gamerson can we merge the properties plugin into worksapce plugin?

**Comment by gamerson** [comment]
hey @simonjhy  yes we could apply the properties plugin inside of our workspace, RootProjectConfigurator.

**Comment by ling-alan-huang** [comment]
Brain already fixed it. Closing.

**Comment by ling-alan-huang** [comment]
Brian already fixed it, closing.

**Pull request closed without merging**
