### PR TITLE
LPS-196218 Source Formatter standalone throws NPE when formatting a single "testcase" file

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@drewbrokke QA in China will be off on National Day, can you help ask the US QA to scan the test failures? Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@SylviaLuan @austinchiang Can you help scan the test result? Thanks.

**Comment by SylviaLuan** [comment]
Passed! [ci:test:relevant](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2435650500&testrayRunId=2435653290).

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
