### PR TITLE
LPS-170503 Avoid using java.util.stream.Stream and java.util.Optional

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-170503

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the test failures? Thanks.

**Comment by Jeremy-Ch** [comment]
Hi @ling-alan-huang I have checked the failures, they are not related to this pr. Thanks.

/cc @austinchiang

**Comment by ling-alan-huang** [comment]
Thanks @Jeremy-Ch 
Sent the PR to Brain for review: https://github.com/brianchandotcom/liferay-portal/pull/127449

**Pull request closed without merging**
