### PR TITLE
LPS-177111 SF, directly assign variables

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hi @austinchiang Can you help scan the test failures? Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
Hi @ling-alan-huang, 

The failed cases are not related to this pull request [ci:test:relevant](DataDefinitionResourceFactoryImplTest > testHttpServletRequestLocale), can forward the pr via `ci:forward:force`

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Pull request closed without merging**
