### PR TITLE
LPS-192701 Enforce method and variable name for PrintWriter

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@austinchiang Can you help check the failures? Thanks.

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
