### PR TITLE
LPS-177352 Add a new SF property to enable/disable formatting from JavaParser

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://issues.liferay.com/browse/LPS-177352>

This pull request adds a new SF property for enabling/disabling formatting of Java and JSP files from `JavaParser`. By default, SF runs JavaParser to format Java/JSP code. However, it applies a specific Java code styling that users may not want (namely, customers and clients). Thus, users should be allowed to enable/disable JavaParser when executing SF.

Let me know if I need to add/remove/change anything.

### CODE REVIEW

**Comment by kevhlee** [comment]
cc: @qz1010

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hey @kevhlee 

JavaParser is a pre-format that formats or standardizes the code before SF checks.
It can help reduce SF logic, and I think most of our SF checks are depending the output from JavaParser.

If we disable Javaparser, I think most our SF checks will not work correctly or as explected.

For example:
```
	private static
		final 
			Log _log = LogFactoryUtil.
				getLog(JavaServiceObjectCheck.class);

```
W/O JavaParser, if we want to look for `static final` by regex, we have to use `static\s+final` or even `static[\s\S]+final`.

If we want to find a method call, we have to use `\w+\.[\s\S]\w\(`, instead of `\w+\.\w\(`

I think we can't disable it. Otherwise we have to look into ever SF check to find out what cases will be lost, and fix them, but that will be a heavy load work.

Let me know what you think about it.

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
@ling-alan-huang,

Perhaps the alternative could be to disable JavaParser __only__ when executing "Upgrade" checks. Let me know if you think there is another alternative.

**Comment by ling-alan-huang** [comment]
Hi @kevhlee Yes, the JavaParser only affects Java/JSP code.

> I believe the option to turn it off is still important. We could add documentation/warning explaining that turning off JavaParser could break certain checks.

This documentation is important for the customers, otherwise they would complain that SF checks don't work very well everday.

Btw, can you also check if we need to make some changes on 
https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-source-formatter/src/main/java/com/liferay/gradle/plugins/source/formatter/SourceFormatterPlugin.java#L114

I think we can forward the pr when you fininshed checking that file.

**Comment by kevhlee** [comment]
@ling-alan-huang,

Regarding the documentation/warning, I can add that to this pull request. Where do you think I should put the warning?

**Comment by ling-alan-huang** [comment]
@kevhlee I don't know where is the good place to put the warning, you know we can run SF by `ant` and `gradlew`.

Is it the proper place to put the warning messages?
https://github.com/liferay/liferay-portal/tree/master/modules/util/source-formatter

**Comment by kevhlee** [comment]
Hi @ling-alan-huang,

I thought of an idea for the warning. What if we log the warning when executing SF and `java.parser.enabled=false`?

**Comment by ling-alan-huang** [comment]
Hi @kevhlee 
Yes, that's the better way to print the message in the console.

**Comment by ling-alan-huang** [comment]
Btw, is upgrade catagory only used by the customers? I mean do we need to use it in some other repos?

**Comment by kevhlee** [comment]
Technically, customers can use it. The Upgrade checks are only meant for Liferay code, not just for `liferay-portal` but also environments like Liferay workspaces.

**Comment by kevhlee** [comment]
Looks like I need to rebase my changes. I'll add the warning as well.

**Comment by kevhlee** [comment]
See <https://github.com/ling-alan-huang/liferay-portal/pull/1703>

**Pull request closed without merging**
