### PR TITLE
Revert "LPS-190915 Temp fix"

### PR DESCRIPTION
**Pull request by ling-alan-huang**
This reverts commit 642a0fbb4bcf1bc7b49adaf78d3f88246a71741e.

@petershin I am reverting this, because the [fix](https://github.com/brianchandotcom/liferay-portal/pull/139215) is already merged.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@Jeremy-Ch Can I force to forward this PR? Thanks.
/cc @austinchiang

**Comment by Jeremy-Ch** [comment]
Hi @ling-alan-huang Looks like the failures are not related to this pr. Force forwarding should be safe. Thanks.

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
Thanks @Jeremy-Ch

**Pull request closed without merging**
